# Site settings
title: Binghamton Enactus
email: enactus@binghamtonsa.org
description: "Binghamton Enactus"
baseurl: ""
url: "http://binghamtonenactus.org"
twitter_username: bingenactus
github_username:  binghamtonenactus

# Build settings
markdown: kramdown
permalink: pretty
